app:
  zitadel:
    host: localhost
    port: 8080
    admin-pat: 'changeme'
    base-url: 'http://${app.zitadel.host}:${app.zitadel.port}'
    authorization-header: 'Bearer ${app.zitadel.admin-pat}'

grpc:
  client:
    zitadel:
      address: 'static://${app.zitadel.host}:${app.zitadel.port}'
      negotiation-type: plaintext

server:
  port: 9090

spring:
  application:
    name: testcontainers-zitadel-demo

logging:
  level:
    tech.aregall: debug