app:
  zitadel:
    base-url: http://localhost:8080
    authorization-header: 'Bearer asdfg12345gjhkhogierithen_asdfg'

grpc:
  client:
    zitadel:
      address: 'static://localhost:8080'
      negotiation-type: plaintext

server:
  port: 9090

spring:
  application:
    name: testcontainers-zitadel-demo

logging:
  level:
    tech.aregall: debug