name: Build Maven project

on:
  push:

jobs:
  build-mvn-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
          cache: maven

      - name: Set up ZITADEL admin PAT dir
        run: echo "ZITADEL_ADMIN_PAT_DIR=${RUNNER_TEMP}/zitadel-admin-pat" >> $GITHUB_ENV

      - name: Create ZITADEL admin PAT dir
        run: mkdir -p "ZITADEL_ADMIN_PAT_DIR"

      - name: Build with Maven wrapper
        run: ./mvnw clean verify