name: Build Maven project

on:
  push:

jobs:
  build-mvn-project:
    runs-on: ubuntu-latest
    env:
      ZITADEL_INIT_DIR: ${{ runner.temp }}/zitadel-init
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
          cache: maven

      - name: Build with Maven wrapper
        run: ./mvnw clean verify